[project]
name = "Flask_API_Json"
description = "A simple twitter clone application, written in Flask, using Python and a sql data file."
version = "0.0.1"
readme = "README.md"
dependencies = [
    "Flask >= 3.1.0",
    "dotenv >= 1.0.1",
    "Flask-SQLAlchemy >= 3.1.1",
    "PyJWT >= 2.10.1"
]